from __future__ import annotations

import hashlib
import json
import re
import unicodedata
import uuid
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any, Callable
from urllib.parse import urlparse

from brainkit.application.gate import check_write
from brainkit.application.ports import (
    GraphPort,
    IntegrationPort,
    JobSpecPort,
    JudgmentPort,
    SearchIndexPort,
    VaultPort,
)
from brainkit.domain.model import (
    ApplyProposal,
    BrainkitError,
    CITATION_RE,
    FilingMode,
    FilingProposal,
    LintFinding,
    NotFoundError,
    PageOperation,
    PolicyError,
    PrivacyMode,
    ProposalStatus,
    SourceRecord,
    ValidationError,
    WIKI_LINK_RE,
    normalize_branch,
    utc_now,
    validate_schema,
)


FRONTMATTER_BOUNDARY = "---"
GENERATED_MARKER = "<!-- generated by brainkit; do not edit -->"
# File exports leave the vault, so they default to the local boundary and never
# carry never-ingest evidence unless the caller widens it on purpose.
DEFAULT_EXPORT_CONSUMER = "local"
INTEGRATION_TARGETS = ("obsidian", "neo4j", "postgres")
EXPORT_SUFFIXES = {
    "json": "json",
    "graphml": "graphml",
    "cypher": "cypher",
    "neo4j": "cypher",
    "kuzu": "cypher",
    "llms-txt": "txt",
}
# Relatedness budget: enough terms to describe a capture, few enough to keep the
# FTS5 MATCH bounded on the capture hot path.
_RELATED_QUERY_TERMS = 12
_RELATED_CANDIDATES = 20
_RELATED_PAGE_LIMIT = 5
_RELATED_MIN_SHARED_TERMS = 2
_RELATED_TEXT_LIMIT = 20_000

GRAPH_PROJECTION = "graph/graph.json"
VIEWS_PROJECTION = "views"
# `views/` is a tree whose branch maps come and go with the branches that hold
# sources, so the artefact is identified by the one file every run writes:
# `views/home.md`. The recorder, the lint check and `status` all use this anchor,
# so "the artefact exists" means the same thing in all three.
PROJECTION_ANCHORS: dict[str, str] = {
    GRAPH_PROJECTION: GRAPH_PROJECTION,
    VIEWS_PROJECTION: "views/home.md",
}
PROJECTION_COMMANDS: dict[str, str] = {
    GRAPH_PROJECTION: "bk graph",
    VIEWS_PROJECTION: "bk views",
}
# Which registry fields each artefact actually renders, measured by mutating one
# field, regenerating, and diffing the output — not read off the source. Both
# artefacts also cover the whole wiki page set, so that is not per-artefact.
#
# The graph labels a raw node with `original_name` and carries `path`; `views`
# renders both plus the Status and Captured columns. `media_type` and `size`
# reach neither, so re-extracting a document does not age a projection.
PROJECTION_RAW_FIELDS: dict[str, tuple[str, ...]] = {
    GRAPH_PROJECTION: ("path", "original_name"),
    VIEWS_PROJECTION: ("path", "original_name", "status", "captured_at"),
}
PROJECTION_LINT_CODES: dict[str, str] = {
    GRAPH_PROJECTION: "graph.stale",
    VIEWS_PROJECTION: "views.stale",
}


class BrainkitService:
    """Application facade. It coordinates ports without owning infrastructure."""

    def __init__(
        self,
        vault: VaultPort,
        index: SearchIndexPort,
        *,
        judgment: JudgmentPort | None = None,
        jobs: JobSpecPort | None = None,
        graph: GraphPort | None = None,
        integrations: IntegrationPort | None = None,
    ):
        self.vault = vault
        self.index = index
        self.judgment = judgment
        self.jobs = jobs
        self.graph_port = graph
        self.integration_port = integrations

    def gate_check_write(self, target: str, *, agent: str = "claude") -> dict[str, Any]:
        """Decide whether a direct write to ``target`` is allowed by the gate."""
        return check_write(self.vault.root, target, agent=agent).to_dict()

    def capture(
        self, source: str | None, *, text: str | None = None, title: str | None = None
    ) -> dict[str, Any]:
        if text is not None:
            record, created = self.vault.capture_text(
                text, title or "captured-note", ".md"
            )
        elif source and _is_url(source):
            url_title = title or urlparse(source).netloc or "captured-link"
            body = f"# {url_title}\n\n{source}\n"
            record, created = self.vault.capture_text(body, url_title, ".md")
        elif source:
            record, created = self.vault.capture_file(Path(source))
        else:
            raise ValidationError("capture requires a source path, URL, or --text")
        self.index.upsert_raw(self.vault, record)
        self._mark_related_pages_for_review(record)
        return {"created": created, "source": record.to_dict()}

    def reconcile(self) -> dict[str, Any]:
        # The port returns counters; widen here instead of loosening its type.
        result: dict[str, Any] = dict(self.vault.reconcile())
        result["indexed_documents"] = self.index.rebuild(self.vault)
        result["freshness_orphans"] = self._drop_orphaned_freshness()
        return result

    def _drop_orphaned_freshness(self) -> list[str]:
        """Heal freshness state after a wiki page is removed outside the gate.

        The registry is reconciled by content hash; freshness is keyed by path,
        so a deleted page leaves an entry that can never be revived.
        """
        present = set(self.vault.wiki_pages())
        dropped = _orphaned_freshness(self.vault.read_state("freshness"), present)
        if not dropped:
            return []

        def mutate(state: dict[str, Any]) -> dict[str, Any]:
            pages = state.setdefault("pages", {})
            for path in dropped:
                pages.pop(path, None)
            return state

        self.vault.mutate_state("freshness", mutate)
        return dropped

    def file(self, identifier: str, branch: str) -> dict[str, Any]:
        record = self.vault.file_source(identifier, normalize_branch(branch))
        self.index.rebuild(self.vault)
        return {"source": record.to_dict()}

    def reindex(self) -> dict[str, Any]:
        return {"indexed_documents": self.index.rebuild(self.vault)}

    def search(
        self, query: str, limit: int = 10, *, consumer: str = "human"
    ) -> dict[str, Any]:
        if not query.strip():
            raise ValidationError("Search query cannot be empty")
        if limit < 1:
            raise ValidationError("Search limit must be positive")
        _validate_consumer(consumer)
        records = self.vault.registry()
        config = self.vault.config()
        ranked: list[Any] = []
        redacted = 0
        privacy_by_path: dict[str, str] = {}
        candidate_limits = [min(100, limit)]
        expanded_limit = min(100, limit * 3)
        if expanded_limit > candidate_limits[0]:
            candidate_limits.append(expanded_limit)
        for candidate_limit in candidate_limits:
            ranked = []
            redacted = 0
            privacy_by_path = {}
            for hit in self.index.search(query, candidate_limit):
                if hit.content_hash and hit.content_hash in records:
                    privacy = _privacy_for_record(config, records[hit.content_hash])
                else:
                    content = self.vault.read_text(hit.path)
                    privacy = _evidence_privacy(
                        hit.to_dict(), content, records, config
                    )
                if not _consumer_allows(consumer, privacy):
                    redacted += 1
                    continue
                privacy_by_path[hit.path] = privacy.value
                ranked.append(hit)
                if len(ranked) >= limit:
                    break
            if len(ranked) >= limit or redacted == 0:
                break
        target_graph = max(1, limit // 4) if limit >= 4 else 0
        direct_limit = max(1, limit - target_graph) if target_graph else limit
        hits = ranked[:direct_limit]
        reserve = limit - len(hits)
        expanded_candidates = self._expand_link_neighbors(hits, 100)
        expanded = []
        for hit in expanded_candidates:
            content = self.vault.read_text(hit.path)
            privacy = _evidence_privacy(hit.to_dict(), content, records, config)
            if not _consumer_allows(consumer, privacy):
                redacted += 1
                continue
            privacy_by_path[hit.path] = privacy.value
            expanded.append(hit)
            if len(expanded) >= reserve:
                break
        if len(expanded) < reserve:
            hits.extend(ranked[len(hits) : len(hits) + reserve - len(expanded)])
        return {
            "query": query,
            "consumer": consumer,
            "redacted": redacted,
            "count": len(hits) + len(expanded),
            "hits": [
                {
                    **hit.to_dict(),
                    "privacy": privacy_by_path.get(hit.path)
                    or _evidence_privacy(
                        hit.to_dict(),
                        self.vault.read_text(hit.path),
                        records,
                        config,
                    ).value,
                }
                for hit in (*hits, *expanded)
            ],
        }

    def context(
        self,
        query: str,
        *,
        limit: int = 8,
        max_chars: int = 24_000,
        consumer: str = "human",
    ) -> dict[str, Any]:
        _validate_consumer(consumer)
        records = self.vault.registry()
        config = self.vault.config()
        evidence: list[dict[str, Any]] = []
        # A count, never a description. `context` is the payload handed to a
        # cloud model, and the path of a redacted source names the document and
        # the branch it lives in — disclosure in its own right.
        redacted = 0
        if query in records:
            record = records[query]
            privacy = _privacy_for_record(config, record)
            if _consumer_allows(consumer, privacy):
                evidence.append(
                    {
                        "citation": f"source:{record.content_hash}",
                        "path": record.path,
                        "kind": "raw",
                        "branches": [_record_branch(record)],
                        "privacy": privacy.value,
                        "content": self.vault.raw_text(record, max_chars=max_chars),
                    }
                )
            else:
                redacted = 1
        else:
            result = self.search(query, limit, consumer=consumer)
            redacted = int(result["redacted"])
            remaining = max_chars
            for hit in result["hits"]:
                if remaining <= 0:
                    break
                content = self.vault.read_text(hit["path"])
                if hit.get("content_hash") and hit["content_hash"] in records:
                    content = self.vault.raw_text(records[hit["content_hash"]])
                excerpt = _focused_excerpt(content, query, min(4_000, remaining))
                remaining -= len(excerpt)
                branches = _evidence_branches(hit, content, records)
                evidence.append(
                    {
                        "citation": (
                            f"source:{hit['content_hash']}"
                            if hit.get("content_hash")
                            else f"page:{hit['path']}"
                        ),
                        "path": hit["path"],
                        "kind": hit["kind"],
                        "branches": branches,
                        "privacy": hit["privacy"],
                        "version": (
                            self.vault.wiki_version(hit["path"])
                            if hit["kind"] != "raw"
                            else None
                        ),
                        "content": excerpt,
                    }
                )
        return {
            "contract_version": 1,
            "query": query,
            "consumer": consumer,
            "wiki_language": config.wiki_language,
            "evidence": evidence,
            "redacted": redacted,
            "apply_contract": {
                "format": "brainkit.apply-proposal.v1",
                "citation": "[^source:<sha256>]",
                "operations": {
                    "action": "upsert",
                    "kind": "source|entity|concept|synthesis",
                    "slug": "lowercase-kebab-case",
                    "title": "string",
                    "aliases": ["string"],
                    "source_hashes": ["sha256"],
                    "body": "markdown with declared citations and links",
                    "links": ["target-slug"],
                    "metadata": {"human_schema_field": "value"},
                    "base_hash": "required current page hash when updating",
                },
            },
        }

    def apply(self, raw_proposal: dict[str, Any]) -> dict[str, Any]:
        return self._apply_transaction(raw_proposal)

    def _apply_transaction(
        self,
        raw_proposal: dict[str, Any],
        *,
        raw_move: tuple[str, str] | None = None,
    ) -> dict[str, Any]:
        proposal = ApplyProposal.from_dict(raw_proposal)
        request_hash = _stable_payload_hash(proposal.to_dict())
        proposal_id = proposal.proposal_id or request_hash
        prior = self.vault.read_state("applied").get("proposals", {}).get(proposal_id)
        if isinstance(prior, dict):
            if prior.get("request_hash") != request_hash:
                raise ValidationError(
                    "proposal_id was already used for a different payload",
                    details={"proposal_id": proposal_id},
                )
            return {
                "applied": len(prior.get("paths", [])),
                "paths": prior.get("paths", []),
                "transaction_id": prior.get("transaction_id"),
                "proposal_id": proposal_id,
                "idempotent": True,
                "indexed_documents": self.index.stats()["documents"],
            }
        failures, pages, expected_versions, referenced_hashes = (
            self._prepare_apply(proposal)
        )
        if failures:
            raise ValidationError(
                "Apply proposal rejected; no files were written",
                details={"failures": failures},
            )
        transaction = self.vault.commit_wiki_batch(
            pages,
            expected_versions,
            {content_hash: "ingested" for content_hash in referenced_hashes},
            proposal_id,
            request_hash,
            self._freshness_updates(proposal.operations, pages),
            raw_move,
            lambda records: self.index.apply_snapshot(
                self.vault,
                records,
                sorted(pages),
                raw_move[0] if raw_move else None,
            ),
        )
        return {
            "applied": len(pages),
            "paths": sorted(pages),
            "transaction_id": transaction["transaction_id"],
            "proposal_id": proposal_id,
            "idempotent": transaction["idempotent"],
            "indexed_documents": transaction["indexed_documents"],
            "raw_move": transaction.get("raw_move"),
        }

    def lint(self, *, semantic: bool = False) -> dict[str, Any]:
        findings = self._mechanical_lint()
        semantic_report: dict[str, Any] | None = None
        if semantic:
            judgment = self._require_judgment()
            context = self.context("contradictions unsupported claims", limit=20)
            semantic_report = self._run_structured_job(
                judgment,
                job="lint-semantic",
                branches=_context_branches(context),
                variables={"context": json.dumps(context, ensure_ascii=False)},
            )
        return {
            "ok": not any(item.severity == "error" for item in findings),
            "findings": [item.to_dict() for item in findings],
            "semantic_report": semantic_report,
        }

    def status(self) -> dict[str, Any]:
        records = self.vault.registry()
        pages = self.vault.wiki_pages()
        raw_counts: dict[str, int] = defaultdict(int)
        for record in records.values():
            parts = PurePosixPath(record.path).parts
            branch = parts[1] if len(parts) > 1 else "unknown"
            raw_counts[branch] += 1
        lint_result = self.lint()
        # Read after lint: `_mechanical_lint` refreshes page staleness in place,
        # so reading first would report the state that lint just superseded.
        freshness = self.vault.read_state("freshness")
        return {
            "vault": str(self.vault.root),
            "sources": len(records),
            "pending": sum(record.status == "pending" for record in records.values()),
            "wiki_pages": len(pages),
            "by_branch": dict(sorted(raw_counts.items())),
            "index": self.index.stats(),
            "freshness": _freshness_summary(freshness, present=set(pages)),
            "projections": self._projection_report(freshness, records),
            "enforcement": self._enforcement_state(),
            "healthy": lint_result["ok"],
            "lint_errors": sum(
                finding["severity"] == "error" for finding in lint_result["findings"]
            ),
        }

    def _enforcement_state(self) -> dict[str, Any]:
        """Report which enforcement layers are live for this vault, from disk.

        `hooks install` says what it wrote at the moment it ran; this says what
        is guarding the vault now. They diverge whenever a hook is edited away,
        a settings file is rewritten, or the vault is copied without its git
        directory -- and a layer that is off while everything still reads like
        success is precisely how an invariant ends up guarded by nothing.
        """
        root = self.vault.root
        settings_path = root / ".claude" / "settings.json"
        registered: set[str] = set()
        events: dict[str, set[str]] = {}
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
            hooks = settings.get("hooks")
            if isinstance(hooks, dict):
                for event, groups in hooks.items():
                    commands = {
                        str(hook.get("command", ""))
                        for group in groups
                        if isinstance(group, dict)
                        for hook in group.get("hooks", [])
                        if isinstance(hook, dict)
                    }
                    events[event] = commands
                    registered |= commands
        except (OSError, ValueError, AttributeError, TypeError):
            # An unreadable or malformed settings file means "nothing is
            # registered", never an exception out of `bk status`.
            pass

        def registered_under(event: str, path: Path) -> bool:
            """Is ``path`` the script some command on ``event`` actually runs?

            Compared against the resolved path as well as the literal one: on
            macOS a vault under /var resolves to /private/var, so a settings
            file written with either spelling must still read as registered.
            A command may also wrap the script in a shell guard rather than
            naming it alone, so containment counts.
            """
            try:
                resolved = path.resolve()
            except OSError:
                resolved = path
            candidates = {str(path), str(resolved)}
            for command in events.get(event, set()):
                if command in candidates or any(c in command for c in candidates):
                    return True
                # The command may spell the same file a different way. Compare
                # resolved forms, guarded because a command is often a shell
                # snippet rather than a bare path.
                try:
                    if Path(command).resolve() == resolved:
                        return True
                except (OSError, ValueError):
                    continue
            return False

        def hook_layer(
            name: str, script: str, event: str, mechanism: str
        ) -> dict[str, Any]:
            path = root / ".claude" / "hooks" / script
            active = path.is_file() and registered_under(event, path)
            detail = "active"
            if not path.is_file():
                detail = f"{script} is not installed"
            elif not active:
                detail = f"{script} exists but is not registered under {event}"
            return {
                "layer": name,
                "mechanism": mechanism,
                "active": active,
                "detail": detail,
            }

        pre_commit = root / ".git" / "hooks" / "pre-commit"
        try:
            commit_active = pre_commit.is_file() and "lint" in pre_commit.read_text(
                encoding="utf-8"
            )
        except OSError:
            commit_active = False
        # The sentinel is duplicated from the installer rather than imported:
        # the application layer must not depend on interfaces.
        instructions = root / "CLAUDE.md"
        try:
            advisory_active = (
                instructions.is_file()
                and "<!-- brainkit:start -->" in instructions.read_text(
                    encoding="utf-8"
                )
            )
        except OSError:
            advisory_active = False

        layers = [
            hook_layer(
                "write_gate",
                "brainkit-gate.sh",
                "PreToolUse",
                "Claude Code PreToolUse hook on Write|Edit|MultiEdit",
            ),
            hook_layer(
                "session_status",
                "brainkit-status.sh",
                "SessionStart",
                "Claude Code SessionStart hook reporting vault state",
            ),
            {
                "layer": "commit_lint",
                "mechanism": ".git/hooks/pre-commit running bk lint --changed",
                "active": commit_active,
                "detail": "active"
                if commit_active
                else "the vault is not a git repository or has no brainkit pre-commit hook",
            },
            {
                "layer": "instructions",
                "mechanism": "CLAUDE.md managed block",
                "active": advisory_active,
                "advisory": True,
                "detail": "active" if advisory_active else "no managed block found",
            },
        ]
        return {
            "layers": layers,
            "inactive": [layer["layer"] for layer in layers if not layer["active"]],
            # Specifically the write gate, not "any non-advisory layer is on".
            # session_status is observability and commit_lint catches a bypass
            # only after the fact; neither one keeps a write out of the wiki, so
            # letting either imply `gated` would report a guarded vault that a
            # Write tool can still walk straight into.
            "gated": any(
                layer["active"] for layer in layers if layer["layer"] == "write_gate"
            ),
        }

    def reader_status(self, *, consumer: str = "human") -> dict[str, Any]:
        _validate_consumer(consumer)
        if consumer == "human":
            return self.status()
        records = self.vault.registry()
        config = self.vault.config()
        visible_records = {
            content_hash: record
            for content_hash, record in records.items()
            if _consumer_allows(consumer, _privacy_for_record(config, record))
        }
        graph = self.graph_data(consumer=consumer)
        visible_pages = {
            str(node["path"])
            for node in graph["nodes"]
            if str(node["id"]).startswith("page:")
        }
        visible_paths = {
            *(record.path for record in visible_records.values()),
            *visible_pages,
        }
        findings = self.lint()["findings"]
        visible_findings = [
            finding
            for finding in findings
            if not finding.get("path") or finding["path"] in visible_paths
        ]
        raw_counts: dict[str, int] = defaultdict(int)
        for record in visible_records.values():
            raw_counts[_record_branch(record)] += 1
        freshness = self.vault.read_state("freshness")
        filtered_freshness = {
            **freshness,
            "pages": {
                path: value
                for path, value in freshness.get("pages", {}).items()
                if path in visible_pages
            },
        }
        index_state = self.index.stats()
        return {
            "vault": str(self.vault.root),
            "sources": len(visible_records),
            "pending": sum(
                record.status == "pending" for record in visible_records.values()
            ),
            "wiki_pages": len(visible_pages),
            "by_branch": dict(sorted(raw_counts.items())),
            "index": {
                **index_state,
                "documents": len(visible_records) + len(visible_pages),
            },
            "freshness": _freshness_summary(filtered_freshness),
            "healthy": not any(
                finding["severity"] == "error" for finding in visible_findings
            ),
            "lint_errors": sum(
                finding["severity"] == "error" for finding in visible_findings
            ),
            "consumer": consumer,
            "redacted_sources": len(records) - len(visible_records),
            "redacted_pages": len(self.vault.wiki_pages()) - len(visible_pages),
        }

    def browse_sources(
        self, *, consumer: str = "human", limit: int = 500
    ) -> dict[str, Any]:
        _validate_consumer(consumer)
        if not 1 <= limit <= 1_000:
            raise ValidationError("Source browse limit must be between 1 and 1000")
        config = self.vault.config()
        records = sorted(
            self.vault.registry().values(),
            key=lambda record: record.captured_at,
            reverse=True,
        )
        visible = []
        redacted = 0
        for record in records:
            privacy = _privacy_for_record(config, record)
            if not _consumer_allows(consumer, privacy):
                redacted += 1
                continue
            visible.append(
                {
                    "id": f"raw:{record.content_hash}",
                    "content_hash": record.content_hash,
                    "path": record.path,
                    "title": record.original_name,
                    "branch": _record_branch(record),
                    "privacy": privacy.value,
                    "status": record.status,
                    "captured_at": record.captured_at,
                    "size": record.size,
                    "media_type": record.media_type,
                }
            )
            if len(visible) >= limit:
                break
        return {
            "consumer": consumer,
            "count": len(visible),
            "redacted": redacted,
            "sources": visible,
        }

    def browse_pages(
        self, *, consumer: str = "human", limit: int = 500
    ) -> dict[str, Any]:
        _validate_consumer(consumer)
        if not 1 <= limit <= 1_000:
            raise ValidationError("Page browse limit must be between 1 and 1000")
        records = self.vault.registry()
        config = self.vault.config()
        freshness = self.vault.read_state("freshness").get("pages", {})
        graph = self.graph_data(consumer=consumer)
        pages = []
        for node in graph["nodes"]:
            if not str(node["id"]).startswith("page:"):
                continue
            path = str(node["path"])
            content = self.vault.read_text(path)
            privacy = _evidence_privacy(node, content, records, config)
            page_freshness = freshness.get(path, {})
            pages.append(
                {
                    **node,
                    "privacy": privacy.value,
                    "freshness": (
                        page_freshness.get("status", "unknown")
                        if isinstance(page_freshness, dict)
                        else "unknown"
                    ),
                    "updated_at": (
                        page_freshness.get("updated_at")
                        if isinstance(page_freshness, dict)
                        else None
                    ),
                }
            )
        pages.sort(key=lambda page: (str(page["kind"]), str(page["label"])))
        return {
            "consumer": consumer,
            "count": min(len(pages), limit),
            "redacted": graph["redacted_nodes"],
            "pages": pages[:limit],
        }

    def timeline(
        self, *, consumer: str = "human", limit: int = 500
    ) -> dict[str, Any]:
        sources = self.browse_sources(consumer=consumer, limit=limit)
        pages = self.browse_pages(consumer=consumer, limit=limit)
        events = [
            {
                "at": source["captured_at"],
                "type": "captured",
                "id": source["id"],
                "title": source["title"],
                "detail": source["branch"],
            }
            for source in sources["sources"]
        ]
        events.extend(
            {
                "at": page["updated_at"],
                "type": "compiled",
                "id": page["id"],
                "title": page["label"],
                "detail": page["freshness"],
            }
            for page in pages["pages"]
            if page["updated_at"]
        )
        events.sort(key=lambda event: str(event["at"]), reverse=True)
        return {
            "consumer": consumer,
            "count": min(len(events), limit),
            "events": events[:limit],
        }

    def views(self, *, consumer: str = "human") -> dict[str, Any]:
        _validate_consumer(consumer)
        status = self.status()
        config = self.vault.config()
        all_records = self.vault.registry()
        records = {
            content_hash: record
            for content_hash, record in all_records.items()
            if _consumer_allows(consumer, _privacy_for_record(config, record))
        }
        freshness = self.vault.read_state("freshness").get("pages", {})
        pages = {}
        for path in self.vault.wiki_pages():
            content = self.vault.read_text(path)
            privacy = _evidence_privacy({"path": path}, content, all_records, config)
            if _consumer_allows(consumer, privacy):
                pages[path] = content
        home = [
            GENERATED_MARKER,
            "# Brainkit",
            "",
            f"- Sources: **{len(records)}**",
            f"- Pending ingestion: "
            f"**{sum(record.status == 'pending' for record in records.values())}**",
            f"- Wiki pages: **{len(pages)}**",
            f"- Health: **{'healthy' if status['healthy'] else 'needs attention'}**",
            "",
            "## Branches",
            "",
        ]
        written = ["views/home.md"]
        by_branch: dict[str, list[SourceRecord]] = defaultdict(list)
        for record in sorted(records.values(), key=lambda item: item.path):
            by_branch[_view_branch(record)].append(record)
        # Every known branch is rewritten, including the ones the consumer cannot
        # see, so a narrower run always overwrites a wider run's rows.
        for branch in status["by_branch"]:
            safe_branch = branch.replace("/", "-")
            view_path = f"views/map/{safe_branch}.md"
            visible = by_branch.get(branch, [])
            home.append(f"- [[map/{safe_branch}|{branch}]] — {len(visible)} sources")
            rows = [
                GENERATED_MARKER,
                f"# {branch}",
                "",
                "| Raw source | Wiki pages | Freshness | Status | Captured |",
                "| --- | --- | --- | --- | --- |",
            ]
            for record in visible:
                linked_paths = [
                    path
                    for path, content in pages.items()
                    if record.content_hash in content
                ]
                linked = [
                    f"[[{PurePosixPath(path).stem}]]" for path in linked_paths
                ]
                freshness_badges = sorted(
                    {
                        str(freshness.get(path, {}).get("status", "unknown"))
                        for path in linked_paths
                    }
                )
                rows.append(
                    "| "
                    f"[[../{record.path}|{record.original_name}]] | "
                    f"{', '.join(linked) or '—'} | "
                    f"{', '.join(freshness_badges) or '—'} | {record.status} | "
                    f"{record.captured_at[:10]} |"
                )
            self.vault.write_generated(view_path, "\n".join(rows) + "\n")
            written.append(view_path)
        self.vault.write_generated("views/home.md", "\n".join(home) + "\n")
        self._record_projection(VIEWS_PROJECTION)
        return {"written": written}

    def graph(self, *, html: bool = False) -> dict[str, Any]:
        if not self.graph_port:
            raise BrainkitError("Graph adapter is not configured")
        graph = self.graph_port.build(self.vault)
        self.vault.write_generated(
            "graph/graph.json", json.dumps(graph, indent=2, ensure_ascii=False) + "\n"
        )
        written = ["graph/graph.json"]
        if html:
            self.vault.write_generated(
                "graph/graph.html", self.graph_port.export(graph, "html")
            )
            written.append("graph/graph.html")
        self._record_projection(GRAPH_PROJECTION)
        return {
            "nodes": len(graph["nodes"]),
            "edges": len(graph["edges"]),
            "written": written,
        }

    def graph_data(self, *, consumer: str = "human") -> dict[str, Any]:
        if not self.graph_port:
            raise BrainkitError("Graph adapter is not configured")
        _validate_consumer(consumer)
        graph = self.graph_port.build(self.vault)
        records = self.vault.registry()
        config = self.vault.config()
        allowed: set[str] = set()
        for node in graph["nodes"]:
            node_id = str(node["id"])
            if node_id.startswith("raw:"):
                content_hash = node_id.removeprefix("raw:")
                record = records.get(content_hash)
                if record and _consumer_allows(
                    consumer, _privacy_for_record(config, record)
                ):
                    allowed.add(node_id)
                continue
            path = str(node.get("path", ""))
            content = self.vault.read_text(path)
            privacy = _evidence_privacy(node, content, records, config)
            if _consumer_allows(consumer, privacy):
                allowed.add(node_id)
        return {
            **graph,
            "nodes": [node for node in graph["nodes"] if node["id"] in allowed],
            "edges": [
                edge
                for edge in graph["edges"]
                if edge["source"] in allowed and edge["target"] in allowed
            ],
            "consumer": consumer,
            "redacted_nodes": len(graph["nodes"]) - len(allowed),
        }

    def read_resource(
        self, identifier: str, *, consumer: str = "human"
    ) -> dict[str, Any]:
        _validate_consumer(consumer)
        records = self.vault.registry()
        config = self.vault.config()
        if identifier.startswith("raw:"):
            content_hash = identifier.removeprefix("raw:")
            record = records.get(content_hash)
            if not record:
                raise NotFoundError(
                    "Raw graph resource was not found",
                    details={"identifier": identifier},
                )
            privacy = _privacy_for_record(config, record)
            if not _consumer_allows(consumer, privacy):
                raise PolicyError(
                    "Resource is outside the consumer privacy boundary",
                    details={"privacy": privacy.value, "consumer": consumer},
                )
            return {
                "id": identifier,
                "path": record.path,
                "kind": "raw",
                "title": record.original_name,
                "privacy": privacy.value,
                "content": self.vault.raw_text(record),
            }
        path = identifier.removeprefix("page:")
        if path not in self.vault.wiki_pages():
            raise NotFoundError(
                "Wiki graph resource was not found", details={"identifier": identifier}
            )
        content = self.vault.read_text(path)
        privacy = _evidence_privacy({"path": path}, content, records, config)
        if not _consumer_allows(consumer, privacy):
            raise PolicyError(
                "Resource is outside the consumer privacy boundary",
                details={"privacy": privacy.value, "consumer": consumer},
            )
        metadata, _ = parse_frontmatter(content)
        return {
            "id": f"page:{path}",
            "path": path,
            "kind": str(metadata.get("type", "wiki")),
            "title": str(metadata.get("title", PurePosixPath(path).stem)),
            "privacy": privacy.value,
            "content": content,
        }

    def export(
        self, target: str, *, consumer: str = DEFAULT_EXPORT_CONSUMER
    ) -> dict[str, Any]:
        if not self.graph_port:
            raise BrainkitError("Graph adapter is not configured")
        _validate_consumer(consumer)
        if target in INTEGRATION_TARGETS:
            # An integration owns its boundary through its own policy. Refuse a
            # different consumer instead of silently widening or narrowing it.
            if consumer != DEFAULT_EXPORT_CONSUMER:
                raise ValidationError(
                    "Integration exports take their consumer from the policy",
                    details={
                        "target": target,
                        "consumer": consumer,
                        "hint": "Set it with integration configure --consumer",
                    },
                )
            return {
                **self.integration_sync(target),
                "consumer": self._integration_consumer(target),
            }
        suffix = EXPORT_SUFFIXES.get(target)
        if suffix is None:
            raise ValidationError("Unsupported export target", details={"target": target})
        graph = self.graph_data(consumer=consumer)
        payload = self.graph_port.export(graph, target)
        path = f"output/export-{target}.{suffix}"
        self.vault.write_generated(path, payload)
        return {"target": target, "path": path, "consumer": consumer}

    def integration_configure(
        self,
        name: str,
        *,
        enabled: bool | None = None,
        managed: bool | None = None,
        options: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        return self._require_integrations().configure(
            name,
            enabled=enabled,
            managed=managed,
            options=options or {},
        )

    def integration_status(self, name: str | None = None) -> dict[str, Any]:
        return self._require_integrations().status(name)

    def integration_up(self, name: str) -> dict[str, Any]:
        if name == "obsidian":
            return self.integration_sync(name)
        return self._require_integrations().up(name)

    def integration_down(self, name: str) -> dict[str, Any]:
        return self._require_integrations().down(name)

    def integration_sync(self, name: str) -> dict[str, Any]:
        graph = self._integration_graph(name)
        if name == "obsidian":
            # Views are copied into the Obsidian vault, so they are generated
            # under the same boundary as the graph that ships with them.
            self.views(consumer=str(graph["consumer"]))
        return self._require_integrations().sync(name, graph)

    def proposals_for_consumer(
        self, status: str | None = None, *, consumer: str = "human"
    ) -> dict[str, Any]:
        _validate_consumer(consumer)
        result = self.proposals(status)
        if consumer == "human":
            return {**result, "consumer": consumer, "redacted": 0}
        records = self.vault.registry()
        config = self.vault.config()
        visible = []
        for proposal in result["proposals"]:
            record = records.get(str(proposal.get("source_hash", "")))
            if record and _consumer_allows(
                consumer, _privacy_for_record(config, record)
            ):
                visible.append(proposal)
        return {
            "count": len(visible),
            "proposals": visible,
            "consumer": consumer,
            "redacted": result["count"] - len(visible),
        }

    def ingest(
        self,
        identifier: str | None = None,
        *,
        all_pending: bool = False,
        target_branch: str | None = None,
    ) -> dict[str, Any]:
        judgment = self._require_judgment()
        records = self.vault.registry()
        if all_pending:
            selected_hashes = [
                item.content_hash
                for item in records.values()
                if item.status == "pending"
            ]
        elif identifier:
            selected_hashes = [
                self._resolve_record(records, identifier).content_hash
            ]
        else:
            raise ValidationError("ingest requires a source identifier or --all")
        results: list[dict[str, Any]] = []
        for content_hash in selected_hashes:
            current_records = self.vault.registry()
            record = current_records[content_hash]
            if all_pending and record.status != "pending":
                continue
            branch = _record_branch(record)
            context = self.context(record.content_hash)
            destination, filing_reason = self._resolve_filing_destination(
                judgment,
                record,
                context,
                target_branch=target_branch,
            )
            apply_payload = self._run_structured_job(
                judgment,
                job="ingest",
                branches=sorted({branch, destination}),
                variables={"context": json.dumps(context, ensure_ascii=False)},
                validator=self._apply_payload_failures,
            )
            apply_payload.setdefault("proposal_id", f"wiki-{uuid.uuid4().hex}")
            filing_policy = self.vault.config().branches[destination].filing
            filing_proposal = FilingProposal(
                proposal_id=f"filing-{uuid.uuid4().hex}",
                source_hash=record.content_hash,
                destination_branch=destination,
                filing_mode=filing_policy,
                apply_proposal=apply_payload,
                reason=filing_reason,
                status=ProposalStatus.PENDING,
                created_at=utc_now(),
            )
            self._save_filing_proposal(filing_proposal)
            if filing_policy == FilingMode.APPROVE_EACH:
                self._set_source_status(record.content_hash, "awaiting-approval")
                results.append(
                    {
                        "source": record.content_hash,
                        "proposal": filing_proposal.to_dict(),
                        "queued": True,
                    }
                )
                continue
            execution = self._execute_filing_proposal(filing_proposal)
            results.append(
                {
                    "source": record.content_hash,
                    "proposal": execution["proposal"],
                    "apply": execution["apply"],
                    "queued": False,
                }
            )
        return {"ingested": len(results), "results": results}

    def proposals(self, status: str | None = None) -> dict[str, Any]:
        selected_status: ProposalStatus | None = None
        if status:
            try:
                selected_status = ProposalStatus(status)
            except ValueError as exc:
                raise ValidationError(
                    "Unknown proposal status", details={"status": status}
                ) from exc
        stored = self.vault.read_state("proposals").get("proposals", {})
        proposals = [
            FilingProposal.from_dict(value)
            for value in stored.values()
            if isinstance(value, dict)
        ]
        if selected_status:
            proposals = [
                proposal
                for proposal in proposals
                if proposal.status == selected_status
            ]
        proposals.sort(key=lambda proposal: proposal.created_at, reverse=True)
        return {
            "count": len(proposals),
            "proposals": [proposal.to_dict() for proposal in proposals],
        }

    def approve(self, proposal_id: str) -> dict[str, Any]:
        proposal = self._get_filing_proposal(proposal_id)
        if proposal.status == ProposalStatus.APPLIED:
            return {
                "proposal": proposal.to_dict(),
                "apply": proposal.result,
                "idempotent": True,
            }
        if proposal.status == ProposalStatus.REJECTED:
            raise ValidationError(
                "Rejected proposal cannot be approved",
                details={"proposal_id": proposal_id},
            )
        return self._execute_filing_proposal(proposal)

    def reject(self, proposal_id: str, reason: str = "") -> dict[str, Any]:
        proposal = self._get_filing_proposal(proposal_id)
        if proposal.status == ProposalStatus.APPLIED:
            raise ValidationError(
                "Applied proposal cannot be rejected",
                details={"proposal_id": proposal_id},
            )
        updated = FilingProposal.from_dict(
            {
                **proposal.to_dict(),
                "status": ProposalStatus.REJECTED.value,
                "decided_at": utc_now(),
                "result": {"reason": reason},
            }
        )
        self._save_filing_proposal(updated)
        self._set_source_status(proposal.source_hash, "rejected")
        return {"proposal": updated.to_dict()}

    def ask(self, question: str, *, save: bool = False) -> dict[str, Any]:
        judgment = self._require_judgment()
        context = self.context(question)
        response = self._run_structured_job(
            judgment,
            job="query",
            branches=_context_branches(context),
            variables={
                "question": question,
                "context": json.dumps(context, ensure_ascii=False),
            },
        )
        answer = str(response["answer"])
        path: str | None = None
        if save:
            slug = re.sub(r"[^a-z0-9]+", "-", question.lower()).strip("-")[:60]
            slug = slug or "answer"
            path = f"output/answers/{utc_now()[:10]}-{slug}.md"
            self.vault.write_generated(
                path, f"# {question}\n\n{answer.rstrip()}\n"
            )
        return {
            "question": question,
            "answer": answer,
            "citations": response["citations"],
            "uncertainty": response["uncertainty"],
            "saved_to": path,
        }

    def digest(self, since: str = "7d") -> dict[str, Any]:
        judgment = self._require_judgment()
        status = self.status()
        recent = sorted(
            self.vault.registry().values(),
            key=lambda item: item.captured_at,
            reverse=True,
        )[:50]
        config = self.vault.config()
        allowed_recent = [
            record
            for record in recent
            if _privacy_for_record(config, record) != PrivacyMode.NEVER_INGEST
        ]
        digest_branches = sorted({_record_branch(record) for record in allowed_recent})
        if not digest_branches:
            digest_branches = ["_inbox"]
        digest_payload = self._run_structured_job(
            judgment,
            job="digest",
            branches=digest_branches,
            variables={
                "since": since,
                "status": json.dumps(status, ensure_ascii=False),
                "sources": json.dumps(
                    [item.to_dict() for item in allowed_recent], ensure_ascii=False
                ),
                "proposals": json.dumps(
                    self.proposals(), ensure_ascii=False
                ),
                "freshness": json.dumps(
                    self.vault.read_state("freshness"), ensure_ascii=False
                ),
            },
        )
        digest = str(digest_payload["markdown"])
        path = f"output/digests/{utc_now()[:10]}.md"
        self.vault.write_generated(path, digest.rstrip() + "\n")
        return {
            "digest": digest,
            "actions": digest_payload["actions"],
            "resurfaced": digest_payload["resurfaced"],
            "path": path,
        }

    def resurface(self) -> dict[str, Any]:
        judgment = self._require_judgment()
        freshness = self.vault.read_state("freshness")
        context = self.context("durable insight worth revisiting", limit=20)
        result = self._run_structured_job(
            judgment,
            job="resurface",
            branches=_context_branches(context),
            variables={"context": json.dumps(context, ensure_ascii=False)},
        )
        path = f"output/resurface/{utc_now()[:10]}.md"
        self.vault.write_generated(path, str(result["markdown"]).rstrip() + "\n")
        page = str(result["page"])

        def mutate(state: dict[str, Any]) -> dict[str, Any]:
            pages = state.setdefault("pages", {})
            entry = pages.setdefault(page, {})
            entry["last_resurfaced_at"] = utc_now()
            return state

        if page in freshness.get("pages", {}) or page in self.vault.wiki_pages():
            self.vault.mutate_state("freshness", mutate)
        return {**result, "path": path}

    def _resolve_filing_destination(
        self,
        judgment: JudgmentPort,
        record: SourceRecord,
        context: dict[str, Any],
        *,
        target_branch: str | None,
    ) -> tuple[str, str]:
        config = self.vault.config()
        current_branch = _record_branch(record)
        if target_branch:
            destination = normalize_branch(target_branch)
            if destination not in config.branches:
                raise ValidationError(
                    "Destination branch is not configured",
                    details={"branch": destination},
                )
            return destination, "Explicit destination supplied by the operator."
        if current_branch != "_inbox":
            if current_branch not in config.branches:
                raise ValidationError(
                    "Current source branch is not configured",
                    details={"branch": current_branch},
                )
            return current_branch, "Source was already filed before ingestion."
        result = self._run_structured_job(
            judgment,
            job="file-proposal",
            branches=["_inbox"],
            variables={
                "context": json.dumps(context, ensure_ascii=False),
                "branches": json.dumps(
                    {
                        branch: {
                            "privacy": policy.privacy.value,
                            "filing": policy.filing.value,
                        }
                        for branch, policy in config.branches.items()
                    },
                    ensure_ascii=False,
                ),
            },
        )
        destination = normalize_branch(str(result.get("branch", "")))
        if destination not in config.branches:
            raise ValidationError(
                "Filing provider proposed an unknown branch",
                details={"branch": destination},
            )
        return destination, str(result.get("reason", ""))

    def _run_structured_job(
        self,
        judgment: JudgmentPort,
        *,
        job: str,
        branches: list[str],
        variables: dict[str, Any],
        max_attempts: int = 3,
        validator: Callable[[dict[str, Any]], list[dict[str, Any]]] | None = None,
    ) -> dict[str, Any]:
        if not self.jobs:
            raise BrainkitError("Job specifications are not configured")
        schema = self.jobs.schema(job)
        if schema is None:
            raise ValidationError(
                "Structured job has no output schema", details={"job": job}
            )
        feedback = ""
        last_failures: list[dict[str, Any]] = []
        last_response = ""
        for attempt in range(1, max_attempts + 1):
            response = judgment.run(
                job=job,
                branches=branches,
                variables={
                    **variables,
                    "repair_feedback": feedback,
                },
                output_schema=schema,
            )
            last_response = response
            try:
                parsed = json.loads(response)
            except json.JSONDecodeError as exc:
                last_failures = [
                    {
                        "path": "$",
                        "code": "json.invalid",
                        "message": str(exc),
                    }
                ]
            else:
                if not isinstance(parsed, dict):
                    last_failures = [
                        {
                            "path": "$",
                            "code": "schema.type",
                            "message": "Expected an object",
                        }
                    ]
                else:
                    last_failures = validate_schema(parsed, schema)
                    if not last_failures and validator:
                        last_failures = validator(parsed)
                    if not last_failures:
                        return parsed
            feedback = json.dumps(
                {
                    "attempt": attempt,
                    "invalid_output": last_response[-8_000:],
                    "validation_failures": last_failures,
                    "instruction": "Return a corrected JSON object only.",
                },
                ensure_ascii=False,
            )
        raise ValidationError(
            "Provider output remained invalid after repair attempts",
            details={
                "job": job,
                "attempts": max_attempts,
                "failures": last_failures,
            },
        )

    def _save_filing_proposal(self, proposal: FilingProposal) -> None:
        def mutate(state: dict[str, Any]) -> dict[str, Any]:
            state.setdefault("version", 1)
            state.setdefault("proposals", {})[proposal.proposal_id] = proposal.to_dict()
            return state

        self.vault.mutate_state("proposals", mutate)

    def _get_filing_proposal(self, proposal_id: str) -> FilingProposal:
        raw = (
            self.vault.read_state("proposals")
            .get("proposals", {})
            .get(proposal_id)
        )
        if not isinstance(raw, dict):
            raise NotFoundError(
                "Filing proposal was not found",
                details={"proposal_id": proposal_id},
            )
        return FilingProposal.from_dict(raw)

    def _execute_filing_proposal(
        self, proposal: FilingProposal
    ) -> dict[str, Any]:
        try:
            records = self.vault.registry()
            record = self._resolve_record(records, proposal.source_hash)
            move = (
                (proposal.source_hash, proposal.destination_branch)
                if _record_branch(record) != proposal.destination_branch
                else None
            )
            apply_result = self._apply_transaction(
                proposal.apply_proposal,
                raw_move=move,
            )
            updated = FilingProposal.from_dict(
                {
                    **proposal.to_dict(),
                    "status": ProposalStatus.APPLIED.value,
                    "decided_at": utc_now(),
                    "result": apply_result,
                }
            )
            self._save_filing_proposal(updated)
            return {"proposal": updated.to_dict(), "apply": apply_result}
        except Exception as exc:
            failed = FilingProposal.from_dict(
                {
                    **proposal.to_dict(),
                    "status": ProposalStatus.FAILED.value,
                    "decided_at": utc_now(),
                    "result": {
                        "error": str(exc),
                        "code": getattr(exc, "code", "execution_error"),
                    },
                }
            )
            self._save_filing_proposal(failed)
            self._set_source_status(proposal.source_hash, "proposal-failed")
            self.index.rebuild(self.vault)
            raise

    def _apply_payload_failures(
        self, raw_proposal: dict[str, Any]
    ) -> list[dict[str, Any]]:
        try:
            proposal = ApplyProposal.from_dict(raw_proposal)
        except BrainkitError as exc:
            return [
                {
                    "path": "$",
                    "code": exc.code,
                    "message": str(exc),
                    **exc.details,
                }
            ]
        failures, _, _, _ = self._prepare_apply(proposal)
        return failures

    def _prepare_apply(
        self, proposal: ApplyProposal
    ) -> tuple[
        list[dict[str, Any]],
        dict[str, str],
        dict[str, str | None],
        set[str],
    ]:
        records = self.vault.registry()
        known_hashes = set(records)
        existing_slugs = self.vault.existing_wiki_slugs()
        proposed_slugs = {operation.slug for operation in proposal.operations}
        catalog = self._wiki_catalog()
        failures: list[dict[str, Any]] = []
        pages: dict[str, str] = {}
        expected_versions: dict[str, str | None] = {}
        referenced_hashes: set[str] = set()
        for operation in proposal.operations:
            failures.extend(
                self._validate_operation(
                    operation, known_hashes, existing_slugs | proposed_slugs
                )
            )
            failures.extend(self._validate_novelty(operation, catalog))
            failures.extend(
                validate_schema(page_metadata(operation), self.vault.schema())
            )
            observed_version = self.vault.wiki_version(operation.relative_path)
            if observed_version is not None and operation.base_hash is None:
                failures.append(
                    {
                        "path": operation.relative_path,
                        "code": "missing_base_hash",
                        "observed": observed_version,
                    }
                )
            elif operation.base_hash != observed_version:
                failures.append(
                    {
                        "path": operation.relative_path,
                        "code": "stale_page",
                        "expected": operation.base_hash,
                        "observed": observed_version,
                    }
                )
            expected_versions[operation.relative_path] = operation.base_hash
            pages[operation.relative_path] = render_page(operation)
            referenced_hashes.update(operation.source_hashes)
            catalog.append(
                {
                    "path": operation.relative_path,
                    "type": operation.kind.value,
                    "title": operation.title,
                    "aliases": list(operation.aliases),
                    "body": operation.body,
                }
            )
        return failures, pages, expected_versions, referenced_hashes

    def _set_source_status(self, content_hash: str, status: str) -> None:
        records = self.vault.registry()
        if content_hash not in records:
            raise NotFoundError(
                "Source was not found", details={"source_hash": content_hash}
            )
        records[content_hash].status = status
        self.vault.save_registry(records)

    def _wiki_catalog(self) -> list[dict[str, Any]]:
        catalog: list[dict[str, Any]] = []
        for path in self.vault.wiki_pages():
            content = self.vault.read_text(path)
            metadata, body = parse_frontmatter(content)
            if metadata.get("type") == "system":
                continue
            catalog.append(
                {
                    "path": path,
                    "type": metadata.get("type"),
                    "title": str(metadata.get("title", PurePosixPath(path).stem)),
                    "aliases": [
                        str(value)
                        for value in metadata.get("aliases", [])
                        if isinstance(value, str)
                    ],
                    "body": body,
                }
            )
        return catalog

    def _validate_novelty(
        self,
        operation: PageOperation,
        catalog: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        failures: list[dict[str, Any]] = []
        policy = self.vault.config().novelty
        proposed_names = {
            _normalize_identity(value)
            for value in (operation.title, *operation.aliases)
            if _normalize_identity(value)
        }
        proposed_tokens = _content_tokens(operation.body)
        for existing in catalog:
            if existing["path"] == operation.relative_path:
                continue
            existing_names = {
                _normalize_identity(value)
                for value in (existing["title"], *existing["aliases"])
                if _normalize_identity(value)
            }
            overlap = sorted(proposed_names & existing_names)
            if overlap:
                failures.append(
                    {
                        "path": operation.relative_path,
                        "code": "duplicate_identity",
                        "existing_path": existing["path"],
                        "values": overlap,
                    }
                )
                continue
            if existing["type"] != operation.kind.value:
                continue
            existing_tokens = _content_tokens(str(existing["body"]))
            union = proposed_tokens | existing_tokens
            similarity = (
                len(proposed_tokens & existing_tokens) / len(union) if union else 1.0
            )
            new_ratio = (
                len(proposed_tokens - existing_tokens) / len(proposed_tokens)
                if proposed_tokens
                else 0.0
            )
            if (
                similarity >= policy.duplicate_similarity_threshold
                and new_ratio < policy.min_new_token_ratio
            ):
                failures.append(
                    {
                        "path": operation.relative_path,
                        "code": "insufficient_novelty",
                        "existing_path": existing["path"],
                        "similarity": round(similarity, 4),
                        "new_token_ratio": round(new_ratio, 4),
                    }
                )
        return failures

    def _freshness_updates(
        self,
        operations: tuple[PageOperation, ...],
        pages: dict[str, str],
    ) -> dict[str, dict[str, Any]]:
        now = utc_now()
        return {
            operation.relative_path: {
                "status": "fresh",
                "updated_at": now,
                "content_hash": hashlib.sha256(
                    pages[operation.relative_path].encode("utf-8")
                ).hexdigest(),
                "source_hashes": list(operation.source_hashes),
                "review_reason": None,
            }
            for operation in operations
        }

    def _mark_related_pages_for_review(self, record: SourceRecord) -> None:
        terms = self._related_query_terms(record)
        if not terms:
            return
        candidates = [
            hit
            for hit in self.index.search(" ".join(terms), limit=_RELATED_CANDIDATES)
            if hit.kind == "wiki"
        ]
        if not candidates:
            return
        # BM25 orders the candidates but has no absolute scale, so a page only
        # counts as related when it actually shares the capture's vocabulary.
        required = min(_RELATED_MIN_SHARED_TERMS, len(terms))
        wanted = set(terms)
        related: list[str] = []
        for hit in candidates:
            shared = wanted & _content_tokens(self.vault.read_text(hit.path))
            if len(shared) < required:
                continue
            related.append(hit.path)
            if len(related) >= _RELATED_PAGE_LIMIT:
                break
        if not related:
            return

        def mutate(state: dict[str, Any]) -> dict[str, Any]:
            pages = state.setdefault("pages", {})
            for path in related:
                entry = pages.setdefault(path, {})
                entry["status"] = "review"
                entry["review_reason"] = f"related source:{record.content_hash}"
                entry["review_requested_at"] = utc_now()
            return state

        self.vault.mutate_state("freshness", mutate)

    def _related_query_terms(self, record: SourceRecord) -> list[str]:
        """Describe a capture by its own text, not by the name it was saved under."""
        text = self.vault.raw_text(record, max_chars=_RELATED_TEXT_LIMIT)
        content = _normalized_tokens(text)
        body_terms = [
            term
            for term, _ in Counter(
                token for token in content if _is_salient_term(token)
            ).most_common(_RELATED_QUERY_TERMS)
        ]
        # The file name only contributes what the document itself corroborates,
        # so a suggestive name cannot stand in for unrelated content.
        seen = set(content)
        name_terms = [
            token
            for token in _normalized_tokens(
                PurePosixPath(record.original_name).stem.replace("-", " ")
            )
            if _is_salient_term(token) and token in seen
        ]
        terms = dict.fromkeys([*name_terms, *body_terms])
        return list(terms)[:_RELATED_QUERY_TERMS]

    def _refresh_staleness(self) -> dict[str, Any]:
        stale_after_days = self.vault.config().novelty.stale_after_days
        now = datetime.now(timezone.utc)

        def mutate(state: dict[str, Any]) -> dict[str, Any]:
            for entry in state.setdefault("pages", {}).values():
                if not isinstance(entry, dict) or entry.get("status") == "review":
                    continue
                updated_at = entry.get("updated_at")
                if not isinstance(updated_at, str):
                    continue
                try:
                    age_days = (now - datetime.fromisoformat(updated_at)).days
                except ValueError:
                    continue
                entry["status"] = (
                    "stale" if age_days >= stale_after_days else "fresh"
                )
                entry["age_days"] = age_days
            return state

        return self.vault.mutate_state("freshness", mutate)

    def _record_projection(self, artifact: str) -> None:
        """Stamp a derived artefact with the inputs it was just built from.

        The page half of the fingerprint is taken inside the mutator, so it is
        computed from the state the write actually commits: an apply landing
        between a read and a write cannot leave a projection claiming to cover
        pages it never saw.

        The registry is read *before* the mutator on purpose. `commit_wiki_batch`
        takes the registry lock before the freshness lock, and both are blocking
        `flock`s, so reading the registry while holding freshness would invert
        the order and deadlock. Reading it first is also the safe direction: a
        capture landing in between is simply absent from the recorded
        fingerprint, and the next lint compares against a registry that has it
        and reports stale. The error can only be a false `stale`, never a false
        `fresh`.
        """
        records = self.vault.registry()
        raw_fields = PROJECTION_RAW_FIELDS[artifact]

        def mutate(state: dict[str, Any]) -> dict[str, Any]:
            projections = state.setdefault("projections", {})
            projections[artifact] = {
                "generated_at": utc_now(),
                "source_hash": _projection_source_hash(
                    state.get("pages", {}), records, raw_fields
                ),
            }
            return state

        self.vault.mutate_state("freshness", mutate)

    def _projection_report(
        self, freshness: dict[str, Any], records: dict[str, SourceRecord]
    ) -> dict[str, Any]:
        """Compare every derived artefact against the inputs it was built from.

        Three outcomes, and they are not the same thing:

        - `missing` — the artefact is not on disk. Nothing derives from the vault
          yet, so nothing can be out of date. `bk graph` and `bk views` are
          on-demand, and a vault that never ran them is not in error.
        - `stale` — the artefact exists but was built from different inputs, or
          from an unrecorded set. A projection whose provenance is unknown is
          treated as out of date rather than trusted.
        - `fresh` — the recorded fingerprint matches the current inputs.

        Each artefact is compared against its own inputs. A shared fingerprint
        would have to cover the union, so a change only one artefact renders
        would age both — and a projection that cries wolf gets ignored, which
        loses the signal by a different route than having no signal at all.
        """
        pages = freshness.get("pages", {})
        recorded = freshness.get("projections", {})
        recorded = recorded if isinstance(recorded, dict) else {}
        now = datetime.now(timezone.utc)
        report: dict[str, Any] = {}
        for artifact, anchor in PROJECTION_ANCHORS.items():
            expected = _projection_source_hash(
                pages, records, PROJECTION_RAW_FIELDS[artifact]
            )
            entry = recorded.get(artifact)
            entry = entry if isinstance(entry, dict) else {}
            generated_at = entry.get("generated_at")
            if not isinstance(generated_at, str):
                generated_at = None
            if self.vault.wiki_version(anchor) is None:
                state = "missing"
            elif entry.get("source_hash") != expected:
                state = "stale"
            else:
                state = "fresh"
            item: dict[str, Any] = {
                "state": state,
                "stale": state == "stale",
                "generated_at": generated_at,
            }
            age_days = _age_in_days(generated_at, now)
            if age_days is not None:
                item["age_days"] = age_days
            report[artifact] = item
        return report

    def _mechanical_lint(self) -> list[LintFinding]:
        findings: list[LintFinding] = []
        freshness = self._refresh_staleness()
        records = self.vault.registry()
        raw_files = set(self.vault.raw_files())
        registered_paths: dict[str, str] = {}
        for content_hash, record in records.items():
            if record.path not in raw_files:
                findings.append(
                    LintFinding(
                        "registry.missing_file",
                        "Registered raw source is missing",
                        path=record.path,
                    )
                )
            else:
                observed_hash = self.vault.content_hash(record.path)
                if observed_hash != content_hash:
                    findings.append(
                        LintFinding(
                            "raw.content_modified",
                            "Raw source content no longer matches its immutable hash",
                            path=record.path,
                        )
                    )
            prior = registered_paths.get(record.path)
            if prior and prior != content_hash:
                findings.append(
                    LintFinding(
                        "registry.path_collision",
                        "Two hashes reference the same raw path",
                        path=record.path,
                    )
                )
            registered_paths[record.path] = content_hash
        for path in sorted(raw_files - set(registered_paths)):
            findings.append(
                LintFinding(
                    "registry.untracked_file",
                    "Raw source is not registered; run bk reconcile",
                    path=path,
                )
            )
        slugs = self.vault.existing_wiki_slugs()
        for path in self.vault.wiki_pages():
            text = self.vault.read_text(path)
            metadata, body = parse_frontmatter(text)
            freshness_entry = freshness.get("pages", {}).get(path)
            is_system_page = metadata.get("type") == "system"
            if not is_system_page and not isinstance(freshness_entry, dict):
                findings.append(
                    LintFinding(
                        "wiki.outside_apply",
                        "Wiki page is not tracked by the apply gate",
                        path=path,
                    )
                )
            elif isinstance(freshness_entry, dict):
                expected_hash = freshness_entry.get("content_hash")
                wiki_observed_hash = self.vault.wiki_version(path)
                if expected_hash and expected_hash != wiki_observed_hash:
                    findings.append(
                        LintFinding(
                            "wiki.outside_apply",
                            "Wiki page changed outside the apply gate",
                            path=path,
                        )
                    )
            for failure in validate_schema(metadata, self.vault.schema()):
                findings.append(
                    LintFinding(
                        failure["code"],
                        failure["message"],
                        path=path,
                    )
                )
            for field in ("id", "type", "title", "aliases", "sources", "updated_at"):
                if field not in metadata:
                    findings.append(
                        LintFinding(
                            "wiki.missing_frontmatter",
                            f"Required frontmatter field is missing: {field}",
                            path=path,
                        )
                    )
            sources = metadata.get("sources", [])
            if not isinstance(sources, list):
                sources = []
                findings.append(
                    LintFinding(
                        "wiki.invalid_sources",
                        "Frontmatter sources must be a list",
                        path=path,
                    )
                )
            for content_hash in sources:
                if content_hash not in records:
                    findings.append(
                        LintFinding(
                            "wiki.unknown_source",
                            f"Unknown source hash: {content_hash}",
                            path=path,
                        )
                    )
            citations = set(CITATION_RE.findall(body))
            for content_hash in citations - set(sources):
                findings.append(
                    LintFinding(
                        "wiki.undeclared_citation",
                        f"Citation is not declared in sources: {content_hash}",
                        path=path,
                    )
                )
            for link in WIKI_LINK_RE.findall(body):
                target = PurePosixPath(link.strip()).name
                if target not in slugs:
                    findings.append(
                        LintFinding(
                            "wiki.unresolved_link",
                            f"Unresolved wiki link: {link.strip()}",
                            path=path,
                        )
                    )
        for path, entry in freshness.get("pages", {}).items():
            if isinstance(entry, dict) and entry.get("status") == "stale":
                findings.append(
                    LintFinding(
                        "wiki.stale",
                        f"Wiki page is stale ({entry.get('age_days', '?')} days)",
                        severity="warning",
                        path=path,
                    )
                )
        for path in _orphaned_freshness(freshness, set(self.vault.wiki_pages())):
            findings.append(
                LintFinding(
                    "freshness.orphaned",
                    "Freshness state tracks a page that no longer exists; "
                    "run bk reconcile",
                    severity="warning",
                    path=path,
                )
            )
        # `freshness` is the state `_refresh_staleness` just committed and
        # `records` the registry this run already read, so the comparison sees
        # exactly the inputs lint reported on without re-reading either. Note
        # the fingerprint leaves out the status and age fields that refresh
        # rewrites on every run, or every lint would invent a stale projection.
        for artifact, report in self._projection_report(freshness, records).items():
            if not report["stale"]:
                continue
            findings.append(
                LintFinding(
                    PROJECTION_LINT_CODES[artifact],
                    f"Derived {artifact} was built from a different set of wiki "
                    f"pages; run {PROJECTION_COMMANDS[artifact]}",
                    severity="warning",
                )
            )
        return findings

    def _validate_operation(
        self,
        operation: PageOperation,
        known_hashes: set[str],
        known_slugs: set[str],
    ) -> list[dict[str, Any]]:
        failures: list[dict[str, Any]] = []
        sources = set(operation.source_hashes)
        unknown = sorted(sources - known_hashes)
        if unknown:
            failures.append(
                {"path": operation.relative_path, "code": "unknown_sources", "values": unknown}
            )
        citations = set(CITATION_RE.findall(operation.body))
        if citations != sources:
            failures.append(
                {
                    "path": operation.relative_path,
                    "code": "citation_mismatch",
                    "missing_citations": sorted(sources - citations),
                    "undeclared_citations": sorted(citations - sources),
                }
            )
        unresolved = sorted(
            link
            for link in operation.links
            if PurePosixPath(link).name not in known_slugs
        )
        if unresolved:
            failures.append(
                {
                    "path": operation.relative_path,
                    "code": "unresolved_links",
                    "values": unresolved,
                }
            )
        return failures

    def _expand_link_neighbors(self, hits: list[Any], remaining: int) -> list[Any]:
        if not hits or remaining <= 0:
            return []
        from brainkit.domain.model import SearchHit

        wiki_hits = [hit for hit in hits if hit.kind.startswith("wiki")]
        if not wiki_hits:
            return []
        known_paths = {hit.path for hit in hits}
        known_slugs = {PurePosixPath(hit.path).stem for hit in wiki_hits}
        outgoing_slugs: set[str] = set()
        for hit in wiki_hits:
            outgoing_slugs.update(
                PurePosixPath(value.strip()).name
                for value in WIKI_LINK_RE.findall(
                    self.vault.read_text(hit.path)
                )
            )
        expanded: list[SearchHit] = []
        for path in self.vault.wiki_pages():
            if path in known_paths:
                continue
            text = self.vault.read_text(path)
            links = {PurePosixPath(v.strip()).name for v in WIKI_LINK_RE.findall(text)}
            if (
                PurePosixPath(path).stem not in outgoing_slugs
                and not (links & known_slugs)
            ):
                continue
            metadata, body = parse_frontmatter(text)
            expanded.append(
                SearchHit(
                    path=path,
                    kind="wiki-neighbor",
                    title=str(metadata.get("title", PurePosixPath(path).stem)),
                    excerpt=_focused_excerpt(body, "", 300),
                    score=0.0,
                )
            )
            if len(expanded) >= remaining:
                break
        return expanded

    @staticmethod
    def _resolve_record(
        records: dict[str, SourceRecord], identifier: str
    ) -> SourceRecord:
        if identifier in records:
            return records[identifier]
        matches = [
            record
            for content_hash, record in records.items()
            if content_hash.startswith(identifier) or record.path == identifier
        ]
        if len(matches) == 1:
            return matches[0]
        if not matches:
            raise NotFoundError("Source was not found", details={"identifier": identifier})
        raise ValidationError(
            "Source identifier is ambiguous", details={"identifier": identifier}
        )

    def _require_judgment(self) -> JudgmentPort:
        if not self.judgment:
            raise BrainkitError("Judgment layer is not configured")
        return self.judgment

    def _require_integrations(self) -> IntegrationPort:
        if not self.integration_port:
            raise BrainkitError("Integration adapters are not configured")
        return self.integration_port

    def _build_graph(self) -> dict[str, Any]:
        if not self.graph_port:
            raise BrainkitError("Graph adapter is not configured")
        return self.graph_port.build(self.vault)

    def _integration_consumer(self, name: str) -> str:
        config = self.vault.config()
        policy = config.integrations.get(name)
        if policy is None:
            raise ValidationError(
                "Unknown integration", details={"integration": name}
            )
        consumer = str(policy.options.get("consumer", ""))
        if not consumer:
            # Obsidian writes to a directory the operator already owns, so an
            # unset consumer falls back to the export default instead of failing.
            if name == "obsidian":
                return DEFAULT_EXPORT_CONSUMER
            raise ValidationError(
                "Integration privacy consumer is not configured",
                details={
                    "integration": name,
                    "hint": "Set consumer to local or cloud before syncing",
                },
            )
        _validate_consumer(consumer)
        return consumer

    def _integration_graph(self, name: str) -> dict[str, Any]:
        return self.graph_data(consumer=self._integration_consumer(name))


def render_page(operation: PageOperation) -> str:
    metadata = page_metadata(operation)
    lines = [FRONTMATTER_BOUNDARY]
    for key, value in metadata.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            lines.extend(f"  - {json.dumps(item, ensure_ascii=False)}" for item in value)
        else:
            lines.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    lines.extend([FRONTMATTER_BOUNDARY, "", f"# {operation.title}", "", operation.body, ""])
    return "\n".join(lines)


def page_metadata(operation: PageOperation) -> dict[str, Any]:
    return {
        "id": operation.page_id,
        "type": operation.kind.value,
        "title": operation.title,
        "aliases": list(operation.aliases),
        "sources": list(operation.source_hashes),
        "updated_at": utc_now(),
        **operation.metadata,
    }


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        return {}, text
    boundary = text.find("\n---\n", 4)
    if boundary < 0:
        return {}, text
    raw = text[4:boundary].splitlines()
    body = text[boundary + 5 :]
    metadata: dict[str, Any] = {}
    current_list: str | None = None
    for line in raw:
        if line.startswith("  - ") and current_list:
            value = line[4:].strip()
            metadata[current_list].append(_parse_yaml_scalar(value))
            continue
        current_list = None
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key, value = key.strip(), value.strip()
        if not value:
            metadata[key] = []
            current_list = key
        else:
            metadata[key] = _parse_yaml_scalar(value)
    return metadata, body


def _parse_yaml_scalar(value: str) -> Any:
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return value


def _is_url(value: str) -> bool:
    return urlparse(value).scheme in {"http", "https"}


def _view_branch(record: SourceRecord) -> str:
    parts = PurePosixPath(record.path).parts
    return parts[1] if len(parts) > 1 else "unknown"


def _record_branch(record: SourceRecord) -> str:
    parts = PurePosixPath(record.path).parts
    if len(parts) < 2 or parts[0] != "raw":
        raise ValidationError("Source is outside raw/", details={"path": record.path})
    return parts[1]


def _evidence_branches(
    hit: dict[str, Any],
    content: str,
    records: dict[str, SourceRecord],
) -> list[str]:
    content_hash = hit.get("content_hash")
    if content_hash and content_hash in records:
        return [_record_branch(records[content_hash])]
    metadata, _ = parse_frontmatter(content)
    source_hashes = metadata.get("sources", [])
    if not isinstance(source_hashes, list):
        return []
    return sorted(
        {
            _record_branch(records[content_hash])
            for content_hash in source_hashes
            if content_hash in records
        }
    )


def _context_branches(context: dict[str, Any]) -> list[str]:
    branches = sorted(
        {
            branch
            for evidence in context.get("evidence", [])
            for branch in evidence.get("branches", [])
        }
    )
    return branches or ["_inbox"]


def _privacy_for_record(config: Any, record: SourceRecord) -> PrivacyMode:
    branch = _record_branch(record)
    policy = config.inbox_policy if branch == "_inbox" else config.branches[branch]
    return policy.privacy


def _evidence_privacy(
    hit: dict[str, Any],
    content: str,
    records: dict[str, SourceRecord],
    config: Any,
) -> PrivacyMode:
    content_hash = hit.get("content_hash")
    if content_hash and content_hash in records:
        return _privacy_for_record(config, records[content_hash])
    metadata, _ = parse_frontmatter(content)
    source_hashes = metadata.get("sources", [])
    if not isinstance(source_hashes, list):
        return PrivacyMode.CLOUD
    modes = [
        _privacy_for_record(config, records[content_hash])
        for content_hash in source_hashes
        if content_hash in records
    ]
    if PrivacyMode.NEVER_INGEST in modes:
        return PrivacyMode.NEVER_INGEST
    if PrivacyMode.LOCAL_ONLY in modes:
        return PrivacyMode.LOCAL_ONLY
    return PrivacyMode.CLOUD


def _validate_consumer(consumer: str) -> None:
    if consumer not in {"human", "local", "cloud"}:
        raise ValidationError(
            "Consumer must be human, local, or cloud",
            details={"consumer": consumer},
        )


def _consumer_allows(consumer: str, privacy: PrivacyMode) -> bool:
    if consumer == "human":
        return True
    if consumer == "local":
        return privacy != PrivacyMode.NEVER_INGEST
    return privacy == PrivacyMode.CLOUD


def _stable_payload_hash(value: dict[str, Any]) -> str:
    return hashlib.sha256(
        json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")
    ).hexdigest()


def _normalize_identity(value: str) -> str:
    normalized = "".join(
        character
        for character in unicodedata.normalize("NFKD", value.casefold())
        if not unicodedata.combining(character)
    )
    return " ".join(re.findall(r"[a-z0-9]+", normalized))


def _normalized_tokens(value: str) -> list[str]:
    without_citations = CITATION_RE.sub("", value)
    normalized = "".join(
        character
        for character in unicodedata.normalize(
            "NFKD", without_citations.casefold()
        )
        if not unicodedata.combining(character)
    )
    return [
        token
        for token in re.findall(r"[a-z0-9]{2,}", normalized)
        if not token.isdigit()
    ]


def _content_tokens(value: str) -> set[str]:
    return set(_normalized_tokens(value))


def _is_salient_term(token: str) -> bool:
    return len(token) >= 3 and token not in _STOPWORDS


# Function words carry no topical signal, and BM25 cannot be trusted to discount
# them in a vault whose corpus is still small.
_STOPWORDS = frozenset(
    """
    about after again against all also although always among and another any are
    around because been before being below best better between both but came can
    cannot come could did does doing done down during each either else enough even
    ever every few first for from further get give goes going gone got had has
    have having her here hers him his how however into its itself just keep kept
    know known last least less let like made make many may maybe might more most
    much must near need never new next nor not now off often once one only onto
    other others our ours out over own per perhaps put quite rather really same
    saw say says see seen shall she should since some soon still such take taken
    than that the their theirs them then there these they thing things this those
    though three through thus too two under until upon use used using very want
    was way well were what when where whether which while who whom whose why will
    with within without would yes yet you your yours
    agora ainda algum alguma algumas alguns ali ano anos antes aos apenas apos
    aquela aquele aqui assim ate bem cada coisa com como contra cujo cuja dela
    dele delas deles depois desde dessa desse desta deste deve devem dizer dos
    das duas ela elas ele eles em entao entre era eram essa esse esta estas este
    estes estao esteve estou eu faz fazer feita feito foi fora foram isso isto
    ja lhe lhes logo mais mas mesma mesmo meu meus minha minhas muito muita
    muitas muitos nao nas nem nessa nesse nesta neste nos nossa nosso num numa
    nunca ou outra outras outro outros para pela pelas pelo pelos pode podem
    poder pois por porque portanto pouco primeira primeiro qual quais quando
    quanto que quem sao sem sempre sendo ser sera seria seu seus sim sobre sua
    suas talvez tambem tem tinha toda todas todo todos tres tudo uma umas uns
    vai vao voce voces
    """.split()
)


def _freshness_summary(
    state: dict[str, Any], *, present: set[str] | None = None
) -> dict[str, int]:
    """Count freshness entries, ignoring pages that no longer exist on disk.

    Deleting a wiki page by hand leaves its entry behind. Counting it would
    report freshness for a page nobody can open; `lint` surfaces the orphan and
    `reconcile` removes it.
    """
    summary: dict[str, int] = {"fresh": 0, "review": 0, "stale": 0, "unknown": 0}
    for path, entry in state.get("pages", {}).items():
        if present is not None and path not in present:
            continue
        status = entry.get("status", "unknown") if isinstance(entry, dict) else "unknown"
        summary[status if status in summary else "unknown"] += 1
    return summary


def _fingerprint_row(namespace: str, *fields: str) -> str:
    """Encode one input row so that no two distinct rows can encode alike.

    The namespace tag comes first, which is what keeps the wiki and raw domains
    apart: a page path can never land in the position a content hash occupies,
    so no transposition of one into the other collides. Every field is then
    length-prefixed, so a separator appearing inside a value cannot fake a field
    boundary either — `("a", "b:c")` and `("a:b", "c")` stay distinct.
    """
    return "|".join([namespace, *(f"{len(field)}:{field}" for field in fields)])


def _projection_source_hash(
    pages: Any,
    records: dict[str, SourceRecord],
    raw_fields: tuple[str, ...],
) -> str:
    """Fingerprint the inputs a derived artefact is built from.

    Deliberately not mtime. A `git checkout` rewrites every mtime in the working
    tree, which would call a current graph stale and — after a checkout that
    restores an old graph — call a stale one current. Content hashes travel with
    the content, so they survive any clone, checkout or rsync.

    Two input domains, because both artefacts render both: the wiki page set,
    and the raw registry. A page-only fingerprint let a `bk capture` add a
    `raw:` node to the graph with nothing reporting it — the exact silent drift
    this check exists to catch. `raw_fields` names the registry fields the
    calling artefact actually renders, so a field only one of them shows cannot
    age the other.

    What stays out: the `status` and `age_days` that `_refresh_staleness`
    rewrites on every `bk lint`. `age_days` reaches no artefact at all, and
    while a page's freshness badge does appear in `views/map/*.md`, that badge
    moves with the clock rather than with anything a user did — folding it in
    would make `views.stale` appear spontaneously on an untouched vault.

    Serialization is pinned so two processes agree: pages sorted by path, raw
    records sorted by content hash, pages before raw, newline between rows,
    UTF-8.
    """
    rows: list[str] = []
    if not isinstance(pages, dict):
        pages = {}
    for path in sorted(pages):
        entry = pages[path]
        content_hash = entry.get("content_hash") if isinstance(entry, dict) else None
        if not isinstance(content_hash, str):
            content_hash = ""
        rows.append(_fingerprint_row("page", path, content_hash))
    for content_hash in sorted(records):
        record = records[content_hash]
        rows.append(
            _fingerprint_row(
                "raw",
                content_hash,
                *(str(getattr(record, field)) for field in raw_fields),
            )
        )
    return hashlib.sha256("\n".join(rows).encode("utf-8")).hexdigest()


def _age_in_days(timestamp: str | None, now: datetime) -> int | None:
    if not timestamp:
        return None
    try:
        moment = datetime.fromisoformat(timestamp)
    except ValueError:
        return None
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=timezone.utc)
    return (now - moment).days


def _orphaned_freshness(state: dict[str, Any], present: set[str]) -> list[str]:
    return sorted(path for path in state.get("pages", {}) if path not in present)


def _focused_excerpt(content: str, query: str, limit: int) -> str:
    compact = re.sub(r"\s+", " ", content).strip()
    if len(compact) <= limit:
        return compact
    tokens = [token.lower() for token in re.findall(r"\w+", query)]
    lowered = compact.lower()
    positions = [lowered.find(token) for token in tokens if lowered.find(token) >= 0]
    center = min(positions) if positions else 0
    start = max(0, center - limit // 4)
    end = min(len(compact), start + limit)
    prefix = "…" if start else ""
    suffix = "…" if end < len(compact) else ""
    return prefix + compact[start:end] + suffix
